<div>
    <header class="page-header"><div><p class="eyebrow">PENGATURAN</p><h1>Outlet & karyawan</h1><p class="muted">Kelola lokasi usaha dan akun tim dengan sederhana.</p></div></header>
    <div class="settings-grid">
        <section class="panel"><div class="panel-head"><div><h2>Tambah outlet</h2><p>Lokasi operasional baru</p></div></div><form wire:submit="addOutlet" class="stack-form">
            <label>Nama outlet<input wire:model="outletName" placeholder="Laundry Pos Kemang">@error('outletName')<small class="form-error">{{ $message }}</small>@enderror</label>
            <div class="form-grid"><label>Kode outlet<input wire:model="outletCode" placeholder="KMG"></label><label>Nomor WhatsApp<input wire:model="outletPhone" placeholder="0812..."></label></div>
            <label>Alamat<textarea wire:model="outletAddress" rows="2"></textarea></label><button class="btn btn-primary">Tambah outlet</button>
        </form></section>
        <section class="panel"><div class="panel-head"><div><h2>Tambah karyawan</h2><p>Akun akan otomatis terhubung ke outlet yang dipilih</p></div></div><form wire:submit="addEmployee" class="stack-form">
            <div class="form-grid"><label>Nama<input wire:model="employeeName">@error('employeeName')<small class="form-error">{{ $message }}</small>@enderror</label><label>Outlet<select wire:model="employeeOutlet"><option value="">Pilih</option>@foreach($outlets->where('is_active', true) as $outlet)<option value="{{ $outlet->id }}">{{ $outlet->name }}</option>@endforeach</select>@error('employeeOutlet')<small class="form-error">{{ $message }}</small>@enderror</label></div>
            <div class="form-grid"><label>Email<input type="email" wire:model="employeeEmail">@error('employeeEmail')<small class="form-error">{{ $message }}</small>@enderror</label><label>No. WhatsApp<input wire:model="employeePhone">@error('employeePhone')<small class="form-error">{{ $message }}</small>@enderror</label></div>
            <label>Password awal<input type="password" wire:model="employeePassword" placeholder="Minimal 8 karakter">@error('employeePassword')<small class="form-error">{{ $message }}</small>@enderror</label>
            <div class="form-grid three"><label>Masuk<input type="time" wire:model="startTime">@error('startTime')<small class="form-error">{{ $message }}</small>@enderror</label><label>Pulang<input type="time" wire:model="endTime">@error('endTime')<small class="form-error">{{ $message }}</small>@enderror</label><label>Toleransi (menit)<input type="number" wire:model="tolerance">@error('tolerance')<small class="form-error">{{ $message }}</small>@enderror</label></div>
            <button class="btn btn-primary">Tambah karyawan</button>
        </form></section>
    </div>
    <section class="panel section-gap"><div class="panel-head"><div><h2>Daftar outlet</h2><p>{{ $outlets->count() }} lokasi operasional</p></div></div><div class="table-wrap"><table><thead><tr><th>Outlet</th><th>Kontak</th><th>Karyawan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
    @forelse($outlets as $outlet)<tr wire:key="outlet-{{ $outlet->id }}"><td><strong>{{ $outlet->name }}</strong><small>{{ $outlet->code }} · {{ $outlet->address ?: 'Alamat belum diisi' }}</small></td><td>{{ $outlet->phone ?: '—' }}</td><td><button type="button" class="btn btn-soft btn-compact" wire:click="viewOutletEmployees({{ $outlet->id }})">{{ $outlet->employees_count }} karyawan</button></td><td><span class="badge {{ $outlet->is_active ? 'badge-success' : 'badge-muted' }}">{{ $outlet->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><div class="row-actions"><button type="button" class="icon-btn" title="Edit outlet" aria-label="Edit {{ $outlet->name }}" wire:click="editOutlet({{ $outlet->id }})">✎</button><button type="button" class="icon-btn danger" title="Hapus outlet" aria-label="Hapus {{ $outlet->name }}" wire:click="confirmDeleteOutlet({{ $outlet->id }})">×</button></div></td></tr>@empty<tr><td colspan="5" class="empty-cell">Belum ada outlet.</td></tr>@endforelse
    </tbody></table></div></section>
    <section class="panel section-gap"><div class="panel-head"><div><h2>Daftar karyawan</h2><p>{{ $employees->count() }} akun karyawan</p></div></div><div class="table-wrap"><table><thead><tr><th>Karyawan</th><th>Outlet</th><th>Jadwal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
    @forelse($employees as $employee)<tr wire:key="employee-{{ $employee->id }}"><td><strong>{{ $employee->name }}</strong><small>{{ $employee->email }}</small></td><td>{{ $employee->outlet?->name ?: 'Belum ditetapkan' }}</td><td>{{ substr($employee->schedule?->start_time ?? '08:00',0,5) }}–{{ substr($employee->schedule?->end_time ?? '17:00',0,5) }}</td><td><button type="button" wire:click="toggleEmployee({{ $employee->id }})" class="badge {{ $employee->is_active?'badge-success':'badge-muted' }}">{{ $employee->is_active?'Aktif':'Nonaktif' }}</button></td><td><div class="row-actions"><button type="button" class="icon-btn" title="Edit karyawan" aria-label="Edit {{ $employee->name }}" wire:click="editEmployee({{ $employee->id }})">✎</button><button type="button" class="icon-btn danger" title="Hapus karyawan" aria-label="Hapus {{ $employee->name }}" wire:click="confirmDeleteEmployee({{ $employee->id }})">×</button></div></td></tr>@empty<tr><td colspan="5" class="empty-cell">Belum ada karyawan.</td></tr>@endforelse
    </tbody></table></div></section>

    @if($editingOutletId)<div class="modal-backdrop" wire:click.self="cancelOutletEdit"><section class="modal"><div class="modal-head"><div><p class="eyebrow">EDIT OUTLET</p><h2>Ubah data outlet</h2></div><button type="button" wire:click="cancelOutletEdit">×</button></div><form wire:submit="updateOutlet" class="form-grid">
        <label class="span-2">Nama outlet<input wire:model="outletName">@error('outletName')<small class="form-error">{{ $message }}</small>@enderror</label>
        <label>Kode outlet<input wire:model="outletCode">@error('outletCode')<small class="form-error">{{ $message }}</small>@enderror</label>
        <label>Nomor WhatsApp<input wire:model="outletPhone"></label>
        <label class="span-2">Alamat<textarea wire:model="outletAddress" rows="3"></textarea></label>
        <label class="span-2">Status<select wire:model="outletIsActive"><option value="1">Aktif</option><option value="0">Nonaktif</option></select></label>
        <div class="form-actions span-2"><button type="button" class="btn btn-ghost" wire:click="cancelOutletEdit">Batal</button><button class="btn btn-primary">Simpan perubahan</button></div>
    </form></section></div>@endif

    @if($deletingOutletId)<div class="modal-backdrop top" wire:click.self="$set('deletingOutletId', null)"><section class="modal small"><div class="modal-head"><div><p class="eyebrow danger-text">HAPUS OUTLET</p><h2>Hapus outlet ini?</h2></div><button type="button" wire:click="$set('deletingOutletId', null)">×</button></div><div class="delete-warning"><strong>Data outlet akan disembunyikan dari operasional.</strong><p>Riwayat transaksi tetap tersimpan. Seluruh akun karyawan pada outlet ini akan dinonaktifkan.</p></div><div class="form-actions"><button type="button" class="btn btn-ghost" wire:click="$set('deletingOutletId', null)">Batal</button><button type="button" class="btn btn-danger" wire:click="deleteOutlet" wire:loading.attr="disabled">Ya, hapus outlet</button></div></section></div>@endif

    @if($editingEmployeeId)<div class="modal-backdrop" wire:click.self="cancelEmployeeEdit"><section class="modal"><div class="modal-head"><div><p class="eyebrow">EDIT KARYAWAN</p><h2>Ubah data karyawan</h2><p class="muted">Outlet terpilih akan otomatis dipakai saat karyawan login.</p></div><button type="button" wire:click="cancelEmployeeEdit">×</button></div><form wire:submit="updateEmployee" class="form-grid">
        <label>Nama<input wire:model="employeeName">@error('employeeName')<small class="form-error">{{ $message }}</small>@enderror</label>
        <label>Outlet<select wire:model="employeeOutlet"><option value="">Pilih</option>@foreach($outlets->where('is_active', true) as $outlet)<option value="{{ $outlet->id }}">{{ $outlet->name }}</option>@endforeach</select>@error('employeeOutlet')<small class="form-error">{{ $message }}</small>@enderror</label>
        <label>Email<input type="email" wire:model="employeeEmail">@error('employeeEmail')<small class="form-error">{{ $message }}</small>@enderror</label>
        <label>No. WhatsApp<input wire:model="employeePhone">@error('employeePhone')<small class="form-error">{{ $message }}</small>@enderror</label>
        <label class="span-2">Password baru <small class="muted">Kosongkan jika tidak ingin mengubah password</small><input type="password" wire:model="employeePassword" placeholder="Minimal 8 karakter">@error('employeePassword')<small class="form-error">{{ $message }}</small>@enderror</label>
        <label>Masuk<input type="time" wire:model="startTime">@error('startTime')<small class="form-error">{{ $message }}</small>@enderror</label>
        <label>Pulang<input type="time" wire:model="endTime">@error('endTime')<small class="form-error">{{ $message }}</small>@enderror</label>
        <label>Toleransi (menit)<input type="number" wire:model="tolerance">@error('tolerance')<small class="form-error">{{ $message }}</small>@enderror</label>
        <label>Status<select wire:model="employeeIsActive"><option value="1">Aktif</option><option value="0">Nonaktif</option></select></label>
        <div class="form-actions span-2"><button type="button" class="btn btn-ghost" wire:click="cancelEmployeeEdit">Batal</button><button class="btn btn-primary">Simpan perubahan</button></div>
    </form></section></div>@endif

    @if($deletingEmployeeId)<div class="modal-backdrop top" wire:click.self="$set('deletingEmployeeId', null)"><section class="modal small"><div class="modal-head"><div><p class="eyebrow danger-text">HAPUS KARYAWAN</p><h2>Hapus akun karyawan?</h2></div><button type="button" wire:click="$set('deletingEmployeeId', null)">×</button></div><div class="delete-warning"><strong>Akun tidak dapat dipakai untuk login lagi.</strong><p>Riwayat transaksi, pembayaran, expense, jadwal, dan absensi karyawan tetap tersimpan.</p></div><div class="form-actions"><button type="button" class="btn btn-ghost" wire:click="$set('deletingEmployeeId', null)">Batal</button><button type="button" class="btn btn-danger" wire:click="deleteEmployee" wire:loading.attr="disabled">Ya, hapus karyawan</button></div></section></div>@endif

    @if($selectedOutlet)<div class="modal-backdrop" wire:click.self="$set('selectedOutletId', null)"><section class="modal"><div class="modal-head"><div><p class="eyebrow">KARYAWAN OUTLET</p><h2>Karyawan di {{ $selectedOutlet->name }}</h2><p class="muted">{{ $outletEmployees->count() }} karyawan di outlet ini</p></div><button type="button" wire:click="$set('selectedOutletId', null)">×</button></div><div class="table-wrap modal-table"><table><thead><tr><th>Karyawan</th><th>Kontak</th><th>Jadwal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
        @forelse($outletEmployees as $employee)<tr wire:key="outlet-employee-{{ $employee->id }}"><td><strong>{{ $employee->name }}</strong><small>{{ $employee->email }}</small></td><td>{{ $employee->phone ?: '—' }}</td><td>{{ substr($employee->schedule?->start_time ?? '08:00',0,5) }}–{{ substr($employee->schedule?->end_time ?? '17:00',0,5) }}</td><td><span class="badge {{ $employee->is_active ? 'badge-success' : 'badge-muted' }}">{{ $employee->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><div class="row-actions"><button type="button" class="icon-btn" title="Edit karyawan" aria-label="Edit {{ $employee->name }}" wire:click="editEmployee({{ $employee->id }})">✎</button><button type="button" class="icon-btn danger" title="Hapus karyawan" aria-label="Hapus {{ $employee->name }}" wire:click="confirmDeleteEmployee({{ $employee->id }})">×</button></div></td></tr>@empty<tr><td colspan="5" class="empty-cell">Belum ada karyawan di outlet ini.</td></tr>@endforelse
    </tbody></table></div></section></div>@endif
</div>
