<div class="pos-page" x-data="{ mobileCartOpen: false }" x-on:order-saved.window="mobileCartOpen = false">
    <header class="page-header compact pos-page-header"><div class="pos-title"><p class="eyebrow">POINT OF SALE</p><h1>Transaksi baru</h1></div><div class="pos-header-actions" x-data="printerControl()"><div class="printer-control"><span>Printer</span><button type="button" class="printer-button" :class="connected?'connected':''" @click="connect()" :disabled="connecting"><span>▧</span><div><strong x-text="connecting?'Menghubungkan...':(connected?'Printer terhubung':'Hubungkan printer')"></strong><small x-text="deviceName||'Bluetooth ESC/POS'"></small></div></button></div>@if(auth()->user()->isOwner())<label class="outlet-select">Outlet<select wire:model.live="outletId">@foreach($outlets as $outlet)<option value="{{ $outlet->id }}">{{ $outlet->name }}</option>@endforeach</select></label>@endif</div></header>
    @if(!$outletId)<div class="alert">Tambahkan outlet terlebih dahulu melalui Pengaturan.</div>@else
    <div class="pos-layout">
        <section class="catalog-panel">
            <div class="search-box large">⌕<input wire:model.live.debounce.250ms="search" placeholder="Cari layanan..."></div>
            <div class="category-pills"><button wire:click="$set('categoryId', null)" class="{{ !$categoryId?'active':'' }}">Semua</button>@foreach($categories as $cat)<button wire:click="$set('categoryId', {{ $cat->id }})" class="{{ $categoryId===$cat->id?'active':'' }}">{{ $cat->name }}</button>@endforeach</div>
            <div class="product-grid">@forelse($products as $product)@php($minimumPrice = $product->activeVariants->min('price') ?? $product->price)<button class="product-card" wire:click="addProduct({{ $product->id }})"><span class="product-symbol">{{ strtoupper(substr($product->name,0,2)) }}</span>@if(isset($cart[(string) $product->id]))<span class="product-cart-qty" aria-label="Jumlah di keranjang">{{ rtrim(rtrim(number_format((float) $cart[(string) $product->id]['quantity'],2,',','.'),'0'),',') }} {{ $product->unit }}</span>@endif<strong>{{ $product->name }}</strong><small>{{ $product->category?->name ?? 'Layanan' }}@if($product->activeVariants->count() > 1) · {{ $product->activeVariants->count() }} varian @endif</small><b>@if($product->activeVariants->count() > 1)<em>Mulai </em>@endif Rp{{ number_format($minimumPrice,0,',','.') }} <em>/{{ $product->unit }}</em></b></button>@empty<div class="empty-state">Tidak ada produk yang ditemukan.</div>@endforelse</div>
        </section>
        <button type="button" class="mobile-cart-backdrop" :class="mobileCartOpen ? 'show' : ''" @click="mobileCartOpen = false" aria-label="Tutup keranjang"></button>
        <aside class="cart-panel" :class="mobileCartOpen ? 'mobile-open' : ''">
            <div class="cart-head"><button type="button" class="mobile-cart-close" @click="mobileCartOpen = false" aria-label="Kembali ke produk">←</button><div><p class="eyebrow">KERANJANG</p><h2>Detail transaksi</h2></div><span>{{ count($cart) }} item</span></div>
            <button class="customer-picker {{ $this->selectedCustomer?'selected':'' }}" wire:click="$set('showCustomer', true)"><span>●</span><div>@if($this->selectedCustomer)<strong>{{ $this->selectedCustomer->name }}</strong><small>{{ $this->selectedCustomer->phone }}</small>@else<strong>Pilih pelanggan</strong><small>Cari atau tambah pelanggan baru</small>@endif</div><b>›</b></button>
            <div class="cart-items">@forelse($cart as $key=>$item)<article><div class="cart-item-main"><div><strong>{{ $item['name'] }}</strong>@if(!$item['variant_required'])<small>{{ $item['variant_name'] }} · {{ $item['duration_hours'] }} jam · Rp{{ number_format($item['price'],0,',','.') }} / {{ $item['unit'] }}</small>@endif</div><button wire:click="removeItem('{{ $key }}')">×</button></div>@if($item['variant_required'])<label class="cart-variant-select"><span>Varian layanan</span><select wire:change="selectVariant('{{ $key }}', $event.target.value)"><option value="">Pilih layanan & harga</option>@foreach($item['variants'] as $variant)<option value="{{ $variant['id'] }}" @selected($item['product_variant_id'] === $variant['id'])>{{ $variant['name'] }} · {{ $variant['duration_hours'] }} jam · Rp{{ number_format($variant['price'],0,',','.') }}</option>@endforeach</select></label>@endif<div class="qty-row"><input type="number" min="0.01" step="0.1" value="{{ $item['quantity'] }}" wire:change="changeQuantity('{{ $key }}', $event.target.value)"><span>{{ $item['unit'] }}</span><strong>@if($item['product_variant_id'] !== null || !$item['variant_required'])Rp{{ number_format(round($item['price']*$item['quantity']),0,',','.') }}@else Pilih varian @endif</strong></div></article>@empty<div class="cart-empty"><span>⌁</span><strong>Keranjang masih kosong</strong><small>Pilih layanan di sebelah kiri</small></div>@endforelse</div>
            @if(count($cart))<div class="cart-controls"><div class="discount-row"><select wire:model.live="discountType"><option value="nominal">Diskon Rp</option><option value="percent">Diskon %</option></select><input type="number" wire:model.live.debounce.300ms="discountValue" min="0"></div><textarea wire:model="notes" rows="2" placeholder="Catatan order (opsional)"></textarea></div>
            <div class="cart-summary"><div><span>Subtotal</span><b>Rp{{ number_format($this->subtotal,0,',','.') }}</b></div>@if($this->discountAmount)<div><span>Diskon</span><b>-Rp{{ number_format($this->discountAmount,0,',','.') }}</b></div>@endif<div class="grand-total"><span>Total</span><b>Rp{{ number_format($this->total,0,',','.') }}</b></div></div>
            <div class="payment-box"><div class="payment-methods">@foreach(['cash'=>'Tunai','transfer'=>'Transfer','qris'=>'QRIS'] as $key=>$label)<button wire:click="$set('paymentMethod','{{ $key }}')" class="{{ $paymentMethod===$key?'active':'' }}">{{ $label }}</button>@endforeach</div><label>Jumlah dibayar<div class="money-input"><span>Rp</span><input type="number" wire:model="paymentAmount" min="0" max="{{ $this->total }}"><button wire:click="setFullPayment">Lunas</button></div></label></div>
            @error('cart')<div class="cart-variant-error">{{ $message }}</div>@enderror
            @if($this->hasUnselectedVariants)<div class="cart-variant-warning">Pilih varian layanan pada semua produk untuk melanjutkan.</div>@endif
            <div class="cart-actions"><button class="btn btn-soft" wire:click="saveOrder(false)" wire:loading.attr="disabled" @disabled($this->hasUnselectedVariants)>Simpan</button><button class="btn btn-primary" wire:click="saveOrder(true)" wire:loading.attr="disabled" @disabled($this->hasUnselectedVariants)>Simpan & cetak</button></div>@endif
        </aside>
    </div>@endif

    @if(count($cart))
        <button type="button" class="mobile-cart-trigger" @click="mobileCartOpen = true">
            <span class="mobile-cart-icon">🛒<b>{{ count($cart) }}</b></span>
            <span><small>Lihat keranjang</small><strong>{{ count($cart) }} item</strong></span>
            <strong>Rp{{ number_format($this->total,0,',','.') }} <i>›</i></strong>
        </button>
    @endif

    @if($showCustomer)<div class="modal-backdrop" wire:click.self="$set('showCustomer', false)"><section class="modal customer-modal"><div class="modal-head"><div><p class="eyebrow">PELANGGAN</p><h2>Pilih pelanggan</h2></div><button wire:click="$set('showCustomer', false)">×</button></div><div class="search-box large">⌕<input wire:model.live.debounce.250ms="customerSearch" placeholder="Cari nama atau WhatsApp..." autofocus></div><button class="add-customer-btn" wire:click="$set('showNewCustomer', true)">＋ <span><strong>Tambah pelanggan baru</strong><small>Data pelanggan belum terdaftar</small></span></button><div class="customer-list">@foreach($customers as $customer)<button wire:click="selectCustomer({{ $customer->id }})"><span>{{ strtoupper(substr($customer->name,0,1)) }}</span><div><strong>{{ $customer->name }}</strong><small>{{ $customer->phone }}</small></div><b>›</b></button>@endforeach</div></section></div>@endif
    @if($showNewCustomer)<div class="modal-backdrop top" wire:click.self="$set('showNewCustomer', false)"><section class="modal"><div class="modal-head"><div><p class="eyebrow">PELANGGAN BARU</p><h2>Tambah pelanggan</h2></div><button wire:click="$set('showNewCustomer', false)">×</button></div><form wire:submit="createCustomer" class="stack-form"><label>Nama pelanggan<input wire:model="newCustomerName" autofocus>@error('newCustomerName')<small class="form-error">{{ $message }}</small>@enderror</label><label>Nomor WhatsApp<input wire:model="newCustomerPhone" inputmode="tel">@error('newCustomerPhone')<small class="form-error">{{ $message }}</small>@enderror</label><label>Alamat (opsional)<textarea wire:model="newCustomerAddress" rows="2"></textarea></label><div class="form-actions"><button type="button" class="btn btn-ghost" wire:click="$set('showNewCustomer', false)">Batal</button><button class="btn btn-primary">Simpan & pilih</button></div></form></section></div>@endif

    @if($this->completedOrder)@php($completedOrder = $this->completedOrder)<div class="modal-backdrop top" wire:click.self="closeCompletedOrder"><section class="modal completed-order-modal"><div class="modal-head"><div><p class="eyebrow">TRANSAKSI BERHASIL</p><h2>{{ $completedOrder->number }}</h2><p class="muted">Detail transaksi {{ $completedOrder->customer_name }}</p></div><button type="button" wire:click="closeCompletedOrder">×</button></div>
        <div class="completed-order-summary"><div><span>Pelanggan</span><strong>{{ $completedOrder->customer_name }}</strong><small>{{ $completedOrder->customer_phone }}</small></div><div><span>Estimasi selesai</span><strong>{{ $completedOrder->due_at?->format('d M Y, H:i') ?? '—' }}</strong><small>{{ $completedOrder->outlet->name }}</small></div></div>
        <div class="completed-order-items">@foreach($completedOrder->items as $item)<article wire:key="completed-order-item-{{ $item->id }}"><div><strong>{{ $item->product_name }}</strong><small>{{ $item->variant_name }}@if($item->duration_hours) · {{ $item->duration_hours }} jam @endif</small><small>{{ rtrim(rtrim(number_format($item->quantity,2,',','.'),'0'),',') }} {{ $item->unit }} × Rp{{ number_format($item->unit_price,0,',','.') }}</small></div><b>Rp{{ number_format($item->subtotal,0,',','.') }}</b></article>@endforeach</div>
        <div class="completed-order-totals"><div><span>Total</span><strong>Rp{{ number_format($completedOrder->total,0,',','.') }}</strong></div><div><span>Dibayar</span><strong>Rp{{ number_format($completedOrder->paid_amount,0,',','.') }}</strong></div><div class="balance"><span>Sisa</span><strong>Rp{{ number_format($completedOrder->balance,0,',','.') }}</strong></div></div>
        <div class="completed-order-actions"><button type="button" class="btn btn-ghost" wire:click="closeCompletedOrder">Transaksi baru</button>@if($completedOrder->whatsapp_url)<a class="btn btn-soft" href="{{ $completedOrder->whatsapp_url }}" target="_blank">Kirim WhatsApp</a>@endif<button type="button" class="btn btn-primary" wire:click="printCompletedOrder" wire:loading.attr="disabled">▧ Cetak ulang</button></div>
    </section></div>@endif
</div>
