<div>
    <header class="page-header"><div><p class="eyebrow">ANALITIK</p><h1>Laporan usaha</h1><p class="muted">Ringkasan transaksi, expense, dan estimasi net profit.</p></div><a class="btn btn-primary" href="{{ route('reports.export', ['from'=>$from, 'to'=>$to, 'outlet_id'=>$outletId]) }}">↓ Export Excel</a></header>
    <section class="report-filter panel"><div class="period-tabs"><button wire:click="setPeriod('today')">Hari ini</button><button wire:click="setPeriod('week')">Minggu ini</button><button wire:click="setPeriod('month')">Bulan ini</button></div><div class="filters">@if($outlets->count()>1)<select wire:model.live="outletId"><option value="">Semua outlet</option>@foreach($outlets as $outlet)<option value="{{ $outlet->id }}">{{ $outlet->name }}</option>@endforeach</select>@endif<input type="date" wire:model.live="from"><span>—</span><input type="date" wire:model.live="to"></div></section>
    <section class="metric-grid report-metrics"><article class="metric-card"><span class="metric-icon blue">Σ</span><div><small>Total penjualan</small><strong>Rp{{ number_format($sales,0,',','.') }}</strong><em>{{ $transactions }} transaksi</em></div></article><article class="metric-card"><span class="metric-icon teal">↓</span><div><small>Pembayaran diterima</small><strong>Rp{{ number_format($received,0,',','.') }}</strong><em>Uang masuk periode ini</em></div></article><article class="metric-card"><span class="metric-icon amber">&#8599;&#65038;</span><div><small>Expense</small><strong>Rp{{ number_format($expenseTotal,0,',','.') }}</strong><em>Pengeluaran tercatat</em></div></article><article class="metric-card {{ $profit>=0?'profit':'loss' }}"><span class="metric-icon">◆</span><div><small>Estimasi net profit</small><strong>Rp{{ number_format($profit,0,',','.') }}</strong><em>Pembayaran − expense</em></div></article></section>
    <div class="report-grid"><section class="panel"><div class="panel-head"><div><h2>Produk terlaris</h2><p>Berdasarkan nilai penjualan</p></div></div><div class="ranking-list">@forelse($topProducts as $item)<div><span>{{ $loop->iteration }}</span><div><strong>{{ $item->product_name }}</strong><small>{{ rtrim(rtrim(number_format($item->qty,2,',','.'),'0'),',') }} unit terjual</small></div><b>Rp{{ number_format($item->revenue,0,',','.') }}</b></div>@empty<p class="empty-cell">Belum ada data.</p>@endforelse</div></section><section class="panel"><div class="panel-head"><div><h2>Expense per kategori</h2><p>Komposisi pengeluaran</p></div></div><div class="ranking-list">@forelse($expenseByCategory as $item)<div><span class="rose">&#8599;&#65038;</span><div><strong>{{ $item->category }}</strong><small>{{ $expenseTotal?round($item->total/$expenseTotal*100):0 }}% dari expense</small></div><b>Rp{{ number_format($item->total,0,',','.') }}</b></div>@empty<p class="empty-cell">Belum ada data.</p>@endforelse</div></section></div>
    <div class="info-note"><strong>Catatan laporan</strong><p>Estimasi net profit dihitung dari pembayaran yang benar-benar diterima dikurangi expense tercatat. Piutang transaksi saat ini sebesar <strong>Rp{{ number_format($receivables,0,',','.') }}</strong> dan tidak dihitung sebagai uang masuk.</p></div>
    <section class="panel section-gap"><div class="panel-head"><div><h2>Semua transaksi</h2><p>Transaksi lunas tetap disimpan dan ditampilkan bersama status pembayaran lainnya.</p></div><label class="per-page-control"><span>Tampilkan</span><select wire:model.live="ordersPerPage">@foreach([10,25,50,100] as $size)<option value="{{ $size }}">{{ $size }} data</option>@endforeach</select></label></div><div class="table-wrap"><table><thead><tr><th>Order</th><th>Pelanggan</th><th>Outlet</th><th>Status</th><th>Pembayaran</th><th>Total</th><th>Dibayar</th><th>Sisa</th></tr></thead><tbody>@forelse($reportOrders as $order)<tr wire:key="report-order-{{ $order->id }}"><td><strong>{{ $order->number }}</strong><small>{{ $order->created_at->format('d M Y, H:i') }}</small></td><td>{{ $order->customer_name }}</td><td>{{ $order->outlet->name }}</td><td><span class="badge status-{{ $order->status }}">{{ __('status.'.$order->status) }}</span></td><td><span class="badge pay-{{ $order->payment_status }}">{{ __('status.'.$order->payment_status) }}</span></td><td><strong>Rp{{ number_format($order->total,0,',','.') }}</strong></td><td>Rp{{ number_format($order->paid_amount,0,',','.') }}</td><td>Rp{{ number_format($order->balance,0,',','.') }}</td></tr>@empty<tr><td colspan="8" class="empty-cell">Belum ada transaksi pada periode ini.</td></tr>@endforelse</tbody></table></div>{{ $reportOrders->links('components.table-pagination') }}</section>
    <section class="panel section-gap"><div class="panel-head"><div><h2>Detail expense</h2><p>Seluruh pengeluaran pada periode laporan.</p></div><label class="per-page-control"><span>Tampilkan</span><select wire:model.live="expensesPerPage">@foreach([10,25,50,100] as $size)<option value="{{ $size }}">{{ $size }} data</option>@endforeach</select></label></div><div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Kategori</th><th>Outlet</th><th>Keterangan</th><th>Metode</th><th>Bukti</th><th>Nominal</th></tr></thead><tbody>@forelse($reportExpenses as $expense)<tr wire:key="report-expense-{{ $expense->id }}"><td>{{ $expense->expense_date->format('d M Y') }}</td><td><span class="badge badge-soft">{{ $expense->category }}</span></td><td>{{ $expense->outlet->name }}</td><td>{{ $expense->description ?: '—' }}<small>{{ $expense->user->name }}</small></td><td>{{ strtoupper($expense->payment_method) }}</td><td><div class="photo-stack">@foreach($expense->attachments as $photo)<a href="{{ route('expenses.attachment',$photo) }}" target="_blank">{{ $loop->iteration }}</a>@endforeach @if(!$expense->attachments->count())<span class="muted">—</span>@endif</div></td><td><strong>Rp{{ number_format($expense->amount,0,',','.') }}</strong></td></tr>@empty<tr><td colspan="7" class="empty-cell">Belum ada expense pada periode ini.</td></tr>@endforelse</tbody></table></div>{{ $reportExpenses->links('components.table-pagination') }}</section>
    <section class="panel section-gap attendance-report">
        <div class="panel-head">
            <div><h2>Laporan absensi</h2><p>Riwayat kehadiran karyawan pada periode laporan.</p></div>
            <div class="table-head-actions"><div class="attendance-report-summary"><span class="badge badge-soft">{{ $attendanceCount }} kehadiran</span><span class="badge {{ $lateCount ? 'badge-danger' : 'badge-success' }}">{{ $lateCount }} terlambat</span></div><label class="per-page-control"><span>Tampilkan</span><select wire:model.live="attendancesPerPage">@foreach([10,25,50,100] as $size)<option value="{{ $size }}">{{ $size }} data</option>@endforeach</select></label></div>
        </div>
        <div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Karyawan</th><th>Outlet</th><th>Jadwal</th><th>Masuk</th><th>Keluar</th><th>Durasi</th><th>Status</th></tr></thead><tbody>
            @forelse($reportAttendances as $attendance)
                <tr wire:key="report-attendance-{{ $attendance->id }}" class="{{ $attendance->status === 'late' ? 'attendance-late-row' : '' }}">
                    <td>{{ $attendance->attendance_date->format('d M Y') }}</td>
                    <td><strong>{{ $attendance->user->name }}</strong></td>
                    <td>{{ $attendance->outlet->name }}</td>
                    <td>{{ substr($attendance->user->schedule?->start_time ?? '-', 0, 5) }}</td>
                    <td><strong>{{ $attendance->check_in_at?->format('H:i') ?? '—' }}</strong></td>
                    <td>{{ $attendance->check_out_at?->format('H:i') ?? '—' }}</td>
                    <td>@if($attendance->work_duration_minutes !== null){{ intdiv($attendance->work_duration_minutes, 60) }}j {{ $attendance->work_duration_minutes % 60 }}m @else—@endif</td>
                    <td><span class="badge {{ $attendance->status === 'late' ? 'badge-danger' : 'badge-success' }}">{{ $attendance->status === 'late' ? 'Terlambat' : 'Hadir' }}</span></td>
                </tr>
            @empty
                <tr><td colspan="8" class="empty-cell">Belum ada data absensi pada periode ini.</td></tr>
            @endforelse
        </tbody></table></div>{{ $reportAttendances->links('components.table-pagination') }}
    </section>
</div>
