<div>
    <header class="page-header"><div><p class="eyebrow">OPERASIONAL</p><h1>Daftar transaksi</h1><p class="muted">Pantau pembayaran dan progres semua order.</p></div><a href="{{ route('pos') }}" class="btn btn-primary" wire:navigate>＋ Transaksi baru</a></header>
    <section class="panel"><div class="filters"><div class="search-box">⌕<input wire:model.live.debounce.300ms="search" placeholder="Nomor, nama, WhatsApp..."></div>@if(auth()->user()->isOwner())<select wire:model.live="outletId"><option value="">Semua outlet</option>@foreach($outlets as $outlet)<option value="{{ $outlet->id }}">{{ $outlet->name }}</option>@endforeach</select>@endif<select wire:model.live="status"><option value="">Semua status</option>@foreach(['received'=>'Diterima','processing'=>'Diproses','ready'=>'Siap diambil','completed'=>'Selesai','cancelled'=>'Dibatalkan'] as $k=>$v)<option value="{{ $k }}">{{ $v }}</option>@endforeach</select><select wire:model.live="paymentStatus"><option value="">Semua pembayaran</option><option value="unpaid">Belum dibayar</option><option value="partial">Sebagian</option><option value="paid">Lunas</option></select><input type="date" wire:model.live="dateFrom"><input type="date" wire:model.live="dateTo"><label class="per-page-control filter-per-page"><span>Tampilkan</span><select wire:model.live="perPage">@foreach([10,25,50,100] as $size)<option value="{{ $size }}">{{ $size }} data</option>@endforeach</select></label></div>
        <div class="table-wrap"><table><thead><tr><th>Order</th><th>Pelanggan</th><th>Jatuh tempo</th><th>Status</th><th>Pembayaran</th><th>Total</th><th>Aksi</th></tr></thead><tbody>
        @forelse($orders as $order)<tr wire:key="order-{{ $order->id }}"><td><strong>{{ $order->number }}</strong><small>{{ $order->created_at->format('d M Y, H:i') }} · {{ $order->outlet->name }}</small></td><td><strong>{{ $order->customer_name }}</strong><small>{{ $order->customer_phone }}</small></td><td class="{{ $order->due_at?->isPast()&&!in_array($order->status,['ready','completed','cancelled'])?'text-danger':'' }}">{{ $order->due_at?->format('d M, H:i') }}</td><td><select class="status-select status-{{ $order->status }}" wire:change="updateStatus({{ $order->id }}, $event.target.value)">@foreach(['received'=>'Diterima','processing'=>'Diproses','ready'=>'Siap diambil','completed'=>'Selesai','cancelled'=>'Dibatalkan'] as $k=>$v)<option value="{{ $k }}" @selected($order->status===$k)>{{ $v }}</option>@endforeach</select></td><td><span class="badge pay-{{ $order->payment_status }}">{{ __('status.'.$order->payment_status) }}</span><small>Rp{{ number_format($order->paid_amount,0,',','.') }} dibayar</small></td><td><strong>Rp{{ number_format($order->total,0,',','.') }}</strong></td><td><div class="row-actions">@if($order->balance>0)<button class="icon-btn" title="Tambah pembayaran" wire:click="openPayment({{ $order->id }})">Rp</button>@endif<button type="button" class="icon-btn" title="Cetak" wire:click="printOrder({{ $order->id }})" wire:loading.attr="disabled">▧</button>@if($order->whatsapp_url)<a class="icon-btn whatsapp" title="Bagikan WhatsApp" href="{{ $order->whatsapp_url }}" target="_blank">WA</a>@endif</div></td></tr>
        @empty<tr><td colspan="7" class="empty-cell">Transaksi tidak ditemukan.</td></tr>@endforelse
        </tbody></table></div>{{ $orders->links('components.table-pagination') }}
    </section>
    @if($selectedOrderId)<div class="modal-backdrop" wire:click.self="$set('selectedOrderId', null)"><section class="modal small"><div class="modal-head"><div><p class="eyebrow">PEMBAYARAN</p><h2>Tambah pembayaran</h2></div><button wire:click="$set('selectedOrderId', null)">×</button></div><form wire:submit="addPayment" class="stack-form"><label>Jumlah<input type="number" wire:model="paymentAmount">@error('paymentAmount')<small class="form-error">{{ $message }}</small>@enderror</label><label>Metode<select wire:model="paymentMethod"><option value="cash">Tunai</option><option value="transfer">Transfer</option><option value="qris">QRIS</option></select></label><div class="form-actions"><button type="button" class="btn btn-ghost" wire:click="$set('selectedOrderId', null)">Batal</button><button class="btn btn-primary">Simpan pembayaran</button></div></form></section></div>@endif
</div>
